#!/usr/bin/with-contenv bash
# shellcheck shell=bash

echo "### Stopping Varroa ###"

cd "$HOME"

rm varroa_pid

# exec 3>&1 4>&2 3>&- 4>&-

# $1 == 256 if exited unexpectedly, in this case $2 contains the exit code.
# - https://github.com/just-containers/s6-overlay?tab=readme-ov-file#setting-the-exit-code-of-the-container-to-the-exit-code-of-your-main-service
if test "$1" -eq 256 ; then
  e=$((128 + $2))
else
  e="$1"
fi

# we should tell s6 about the exit code, docker will grab it after.
echo "$e" > /run/s6-linux-init-container-results/exitcode